# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jbv/xperiment/webcjson

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jbv/xperiment/webcjson

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jbv/xperiment/webcjson/CMakeFiles /home/jbv/xperiment/webcjson/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jbv/xperiment/webcjson/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stubbed

# Build rule for target.
stubbed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stubbed
.PHONY : stubbed

# fast build rule for target.
stubbed/fast:
	$(MAKE) -f CMakeFiles/stubbed.dir/build.make CMakeFiles/stubbed.dir/build
.PHONY : stubbed/fast

#=============================================================================
# Target rules for targets named web

# Build rule for target.
web: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 web
.PHONY : web

# fast build rule for target.
web/fast:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/build
.PHONY : web/fast

lib/engine/default_service.o: lib/engine/default_service.cpp.o

.PHONY : lib/engine/default_service.o

# target to build an object file
lib/engine/default_service.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/default_service.cpp.o
.PHONY : lib/engine/default_service.cpp.o

lib/engine/default_service.i: lib/engine/default_service.cpp.i

.PHONY : lib/engine/default_service.i

# target to preprocess a source file
lib/engine/default_service.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/default_service.cpp.i
.PHONY : lib/engine/default_service.cpp.i

lib/engine/default_service.s: lib/engine/default_service.cpp.s

.PHONY : lib/engine/default_service.s

# target to generate assembly for a file
lib/engine/default_service.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/default_service.cpp.s
.PHONY : lib/engine/default_service.cpp.s

lib/engine/engine.o: lib/engine/engine.cpp.o

.PHONY : lib/engine/engine.o

# target to build an object file
lib/engine/engine.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/engine.cpp.o
.PHONY : lib/engine/engine.cpp.o

lib/engine/engine.i: lib/engine/engine.cpp.i

.PHONY : lib/engine/engine.i

# target to preprocess a source file
lib/engine/engine.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/engine.cpp.i
.PHONY : lib/engine/engine.cpp.i

lib/engine/engine.s: lib/engine/engine.cpp.s

.PHONY : lib/engine/engine.s

# target to generate assembly for a file
lib/engine/engine.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/engine.cpp.s
.PHONY : lib/engine/engine.cpp.s

lib/engine/http_cache.o: lib/engine/http_cache.cpp.o

.PHONY : lib/engine/http_cache.o

# target to build an object file
lib/engine/http_cache.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_cache.cpp.o
.PHONY : lib/engine/http_cache.cpp.o

lib/engine/http_cache.i: lib/engine/http_cache.cpp.i

.PHONY : lib/engine/http_cache.i

# target to preprocess a source file
lib/engine/http_cache.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_cache.cpp.i
.PHONY : lib/engine/http_cache.cpp.i

lib/engine/http_cache.s: lib/engine/http_cache.cpp.s

.PHONY : lib/engine/http_cache.s

# target to generate assembly for a file
lib/engine/http_cache.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_cache.cpp.s
.PHONY : lib/engine/http_cache.cpp.s

lib/engine/http_context.o: lib/engine/http_context.cpp.o

.PHONY : lib/engine/http_context.o

# target to build an object file
lib/engine/http_context.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_context.cpp.o
.PHONY : lib/engine/http_context.cpp.o

lib/engine/http_context.i: lib/engine/http_context.cpp.i

.PHONY : lib/engine/http_context.i

# target to preprocess a source file
lib/engine/http_context.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_context.cpp.i
.PHONY : lib/engine/http_context.cpp.i

lib/engine/http_context.s: lib/engine/http_context.cpp.s

.PHONY : lib/engine/http_context.s

# target to generate assembly for a file
lib/engine/http_context.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_context.cpp.s
.PHONY : lib/engine/http_context.cpp.s

lib/engine/http_format.o: lib/engine/http_format.cpp.o

.PHONY : lib/engine/http_format.o

# target to build an object file
lib/engine/http_format.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_format.cpp.o
.PHONY : lib/engine/http_format.cpp.o

lib/engine/http_format.i: lib/engine/http_format.cpp.i

.PHONY : lib/engine/http_format.i

# target to preprocess a source file
lib/engine/http_format.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_format.cpp.i
.PHONY : lib/engine/http_format.cpp.i

lib/engine/http_format.s: lib/engine/http_format.cpp.s

.PHONY : lib/engine/http_format.s

# target to generate assembly for a file
lib/engine/http_format.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_format.cpp.s
.PHONY : lib/engine/http_format.cpp.s

lib/engine/http_properties.o: lib/engine/http_properties.cpp.o

.PHONY : lib/engine/http_properties.o

# target to build an object file
lib/engine/http_properties.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_properties.cpp.o
.PHONY : lib/engine/http_properties.cpp.o

lib/engine/http_properties.i: lib/engine/http_properties.cpp.i

.PHONY : lib/engine/http_properties.i

# target to preprocess a source file
lib/engine/http_properties.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_properties.cpp.i
.PHONY : lib/engine/http_properties.cpp.i

lib/engine/http_properties.s: lib/engine/http_properties.cpp.s

.PHONY : lib/engine/http_properties.s

# target to generate assembly for a file
lib/engine/http_properties.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_properties.cpp.s
.PHONY : lib/engine/http_properties.cpp.s

lib/engine/http_secured_server.o: lib/engine/http_secured_server.cpp.o

.PHONY : lib/engine/http_secured_server.o

# target to build an object file
lib/engine/http_secured_server.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_secured_server.cpp.o
.PHONY : lib/engine/http_secured_server.cpp.o

lib/engine/http_secured_server.i: lib/engine/http_secured_server.cpp.i

.PHONY : lib/engine/http_secured_server.i

# target to preprocess a source file
lib/engine/http_secured_server.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_secured_server.cpp.i
.PHONY : lib/engine/http_secured_server.cpp.i

lib/engine/http_secured_server.s: lib/engine/http_secured_server.cpp.s

.PHONY : lib/engine/http_secured_server.s

# target to generate assembly for a file
lib/engine/http_secured_server.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_secured_server.cpp.s
.PHONY : lib/engine/http_secured_server.cpp.s

lib/engine/http_server.o: lib/engine/http_server.cpp.o

.PHONY : lib/engine/http_server.o

# target to build an object file
lib/engine/http_server.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_server.cpp.o
.PHONY : lib/engine/http_server.cpp.o

lib/engine/http_server.i: lib/engine/http_server.cpp.i

.PHONY : lib/engine/http_server.i

# target to preprocess a source file
lib/engine/http_server.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_server.cpp.i
.PHONY : lib/engine/http_server.cpp.i

lib/engine/http_server.s: lib/engine/http_server.cpp.s

.PHONY : lib/engine/http_server.s

# target to generate assembly for a file
lib/engine/http_server.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/http_server.cpp.s
.PHONY : lib/engine/http_server.cpp.s

lib/engine/recorded_service.o: lib/engine/recorded_service.cpp.o

.PHONY : lib/engine/recorded_service.o

# target to build an object file
lib/engine/recorded_service.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/recorded_service.cpp.o
.PHONY : lib/engine/recorded_service.cpp.o

lib/engine/recorded_service.i: lib/engine/recorded_service.cpp.i

.PHONY : lib/engine/recorded_service.i

# target to preprocess a source file
lib/engine/recorded_service.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/recorded_service.cpp.i
.PHONY : lib/engine/recorded_service.cpp.i

lib/engine/recorded_service.s: lib/engine/recorded_service.cpp.s

.PHONY : lib/engine/recorded_service.s

# target to generate assembly for a file
lib/engine/recorded_service.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/recorded_service.cpp.s
.PHONY : lib/engine/recorded_service.cpp.s

lib/engine/service.o: lib/engine/service.cpp.o

.PHONY : lib/engine/service.o

# target to build an object file
lib/engine/service.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/service.cpp.o
.PHONY : lib/engine/service.cpp.o

lib/engine/service.i: lib/engine/service.cpp.i

.PHONY : lib/engine/service.i

# target to preprocess a source file
lib/engine/service.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/service.cpp.i
.PHONY : lib/engine/service.cpp.i

lib/engine/service.s: lib/engine/service.cpp.s

.PHONY : lib/engine/service.s

# target to generate assembly for a file
lib/engine/service.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/service.cpp.s
.PHONY : lib/engine/service.cpp.s

lib/engine/service_loader.o: lib/engine/service_loader.cpp.o

.PHONY : lib/engine/service_loader.o

# target to build an object file
lib/engine/service_loader.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/service_loader.cpp.o
.PHONY : lib/engine/service_loader.cpp.o

lib/engine/service_loader.i: lib/engine/service_loader.cpp.i

.PHONY : lib/engine/service_loader.i

# target to preprocess a source file
lib/engine/service_loader.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/service_loader.cpp.i
.PHONY : lib/engine/service_loader.cpp.i

lib/engine/service_loader.s: lib/engine/service_loader.cpp.s

.PHONY : lib/engine/service_loader.s

# target to generate assembly for a file
lib/engine/service_loader.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/service_loader.cpp.s
.PHONY : lib/engine/service_loader.cpp.s

lib/engine/service_recorder.o: lib/engine/service_recorder.cpp.o

.PHONY : lib/engine/service_recorder.o

# target to build an object file
lib/engine/service_recorder.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/service_recorder.cpp.o
.PHONY : lib/engine/service_recorder.cpp.o

lib/engine/service_recorder.i: lib/engine/service_recorder.cpp.i

.PHONY : lib/engine/service_recorder.i

# target to preprocess a source file
lib/engine/service_recorder.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/service_recorder.cpp.i
.PHONY : lib/engine/service_recorder.cpp.i

lib/engine/service_recorder.s: lib/engine/service_recorder.cpp.s

.PHONY : lib/engine/service_recorder.s

# target to generate assembly for a file
lib/engine/service_recorder.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/engine/service_recorder.cpp.s
.PHONY : lib/engine/service_recorder.cpp.s

lib/http-parser/http_parser.o: lib/http-parser/http_parser.c.o

.PHONY : lib/http-parser/http_parser.o

# target to build an object file
lib/http-parser/http_parser.c.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/http-parser/http_parser.c.o
.PHONY : lib/http-parser/http_parser.c.o

lib/http-parser/http_parser.i: lib/http-parser/http_parser.c.i

.PHONY : lib/http-parser/http_parser.i

# target to preprocess a source file
lib/http-parser/http_parser.c.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/http-parser/http_parser.c.i
.PHONY : lib/http-parser/http_parser.c.i

lib/http-parser/http_parser.s: lib/http-parser/http_parser.c.s

.PHONY : lib/http-parser/http_parser.s

# target to generate assembly for a file
lib/http-parser/http_parser.c.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/http-parser/http_parser.c.s
.PHONY : lib/http-parser/http_parser.c.s

lib/utils/Properties.o: lib/utils/Properties.cpp.o

.PHONY : lib/utils/Properties.o

# target to build an object file
lib/utils/Properties.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/Properties.cpp.o
.PHONY : lib/utils/Properties.cpp.o

lib/utils/Properties.i: lib/utils/Properties.cpp.i

.PHONY : lib/utils/Properties.i

# target to preprocess a source file
lib/utils/Properties.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/Properties.cpp.i
.PHONY : lib/utils/Properties.cpp.i

lib/utils/Properties.s: lib/utils/Properties.cpp.s

.PHONY : lib/utils/Properties.s

# target to generate assembly for a file
lib/utils/Properties.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/Properties.cpp.s
.PHONY : lib/utils/Properties.cpp.s

lib/utils/advanced_string.o: lib/utils/advanced_string.cpp.o

.PHONY : lib/utils/advanced_string.o

# target to build an object file
lib/utils/advanced_string.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/advanced_string.cpp.o
.PHONY : lib/utils/advanced_string.cpp.o

lib/utils/advanced_string.i: lib/utils/advanced_string.cpp.i

.PHONY : lib/utils/advanced_string.i

# target to preprocess a source file
lib/utils/advanced_string.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/advanced_string.cpp.i
.PHONY : lib/utils/advanced_string.cpp.i

lib/utils/advanced_string.s: lib/utils/advanced_string.cpp.s

.PHONY : lib/utils/advanced_string.s

# target to generate assembly for a file
lib/utils/advanced_string.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/advanced_string.cpp.s
.PHONY : lib/utils/advanced_string.cpp.s

lib/utils/compress.o: lib/utils/compress.cpp.o

.PHONY : lib/utils/compress.o

# target to build an object file
lib/utils/compress.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/compress.cpp.o
.PHONY : lib/utils/compress.cpp.o

lib/utils/compress.i: lib/utils/compress.cpp.i

.PHONY : lib/utils/compress.i

# target to preprocess a source file
lib/utils/compress.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/compress.cpp.i
.PHONY : lib/utils/compress.cpp.i

lib/utils/compress.s: lib/utils/compress.cpp.s

.PHONY : lib/utils/compress.s

# target to generate assembly for a file
lib/utils/compress.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/compress.cpp.s
.PHONY : lib/utils/compress.cpp.s

lib/utils/demangle.o: lib/utils/demangle.cpp.o

.PHONY : lib/utils/demangle.o

# target to build an object file
lib/utils/demangle.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/demangle.cpp.o
.PHONY : lib/utils/demangle.cpp.o

lib/utils/demangle.i: lib/utils/demangle.cpp.i

.PHONY : lib/utils/demangle.i

# target to preprocess a source file
lib/utils/demangle.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/demangle.cpp.i
.PHONY : lib/utils/demangle.cpp.i

lib/utils/demangle.s: lib/utils/demangle.cpp.s

.PHONY : lib/utils/demangle.s

# target to generate assembly for a file
lib/utils/demangle.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/demangle.cpp.s
.PHONY : lib/utils/demangle.cpp.s

lib/utils/files.o: lib/utils/files.cpp.o

.PHONY : lib/utils/files.o

# target to build an object file
lib/utils/files.cpp.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/files.cpp.o
.PHONY : lib/utils/files.cpp.o

lib/utils/files.i: lib/utils/files.cpp.i

.PHONY : lib/utils/files.i

# target to preprocess a source file
lib/utils/files.cpp.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/files.cpp.i
.PHONY : lib/utils/files.cpp.i

lib/utils/files.s: lib/utils/files.cpp.s

.PHONY : lib/utils/files.s

# target to generate assembly for a file
lib/utils/files.cpp.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/files.cpp.s
.PHONY : lib/utils/files.cpp.s

lib/utils/jsonxx/jsonxx.o: lib/utils/jsonxx/jsonxx.cc.o

.PHONY : lib/utils/jsonxx/jsonxx.o

# target to build an object file
lib/utils/jsonxx/jsonxx.cc.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/jsonxx/jsonxx.cc.o
.PHONY : lib/utils/jsonxx/jsonxx.cc.o

lib/utils/jsonxx/jsonxx.i: lib/utils/jsonxx/jsonxx.cc.i

.PHONY : lib/utils/jsonxx/jsonxx.i

# target to preprocess a source file
lib/utils/jsonxx/jsonxx.cc.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/jsonxx/jsonxx.cc.i
.PHONY : lib/utils/jsonxx/jsonxx.cc.i

lib/utils/jsonxx/jsonxx.s: lib/utils/jsonxx/jsonxx.cc.s

.PHONY : lib/utils/jsonxx/jsonxx.s

# target to generate assembly for a file
lib/utils/jsonxx/jsonxx.cc.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/jsonxx/jsonxx.cc.s
.PHONY : lib/utils/jsonxx/jsonxx.cc.s

lib/utils/trex/trex.o: lib/utils/trex/trex.c.o

.PHONY : lib/utils/trex/trex.o

# target to build an object file
lib/utils/trex/trex.c.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/trex/trex.c.o
.PHONY : lib/utils/trex/trex.c.o

lib/utils/trex/trex.i: lib/utils/trex/trex.c.i

.PHONY : lib/utils/trex/trex.i

# target to preprocess a source file
lib/utils/trex/trex.c.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/trex/trex.c.i
.PHONY : lib/utils/trex/trex.c.i

lib/utils/trex/trex.s: lib/utils/trex/trex.c.s

.PHONY : lib/utils/trex/trex.s

# target to generate assembly for a file
lib/utils/trex/trex.c.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/lib/utils/trex/trex.c.s
.PHONY : lib/utils/trex/trex.c.s

server.o: server.cc.o

.PHONY : server.o

# target to build an object file
server.cc.o:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/server.cc.o
.PHONY : server.cc.o

server.i: server.cc.i

.PHONY : server.i

# target to preprocess a source file
server.cc.i:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/server.cc.i
.PHONY : server.cc.i

server.s: server.cc.s

.PHONY : server.s

# target to generate assembly for a file
server.cc.s:
	$(MAKE) -f CMakeFiles/web.dir/build.make CMakeFiles/web.dir/server.cc.s
.PHONY : server.cc.s

stubs/service_module_context.o: stubs/service_module_context.cpp.o

.PHONY : stubs/service_module_context.o

# target to build an object file
stubs/service_module_context.cpp.o:
	$(MAKE) -f CMakeFiles/stubbed.dir/build.make CMakeFiles/stubbed.dir/stubs/service_module_context.cpp.o
.PHONY : stubs/service_module_context.cpp.o

stubs/service_module_context.i: stubs/service_module_context.cpp.i

.PHONY : stubs/service_module_context.i

# target to preprocess a source file
stubs/service_module_context.cpp.i:
	$(MAKE) -f CMakeFiles/stubbed.dir/build.make CMakeFiles/stubbed.dir/stubs/service_module_context.cpp.i
.PHONY : stubs/service_module_context.cpp.i

stubs/service_module_context.s: stubs/service_module_context.cpp.s

.PHONY : stubs/service_module_context.s

# target to generate assembly for a file
stubs/service_module_context.cpp.s:
	$(MAKE) -f CMakeFiles/stubbed.dir/build.make CMakeFiles/stubbed.dir/stubs/service_module_context.cpp.s
.PHONY : stubs/service_module_context.cpp.s

stubs/service_module_fibo.o: stubs/service_module_fibo.cpp.o

.PHONY : stubs/service_module_fibo.o

# target to build an object file
stubs/service_module_fibo.cpp.o:
	$(MAKE) -f CMakeFiles/stubbed.dir/build.make CMakeFiles/stubbed.dir/stubs/service_module_fibo.cpp.o
.PHONY : stubs/service_module_fibo.cpp.o

stubs/service_module_fibo.i: stubs/service_module_fibo.cpp.i

.PHONY : stubs/service_module_fibo.i

# target to preprocess a source file
stubs/service_module_fibo.cpp.i:
	$(MAKE) -f CMakeFiles/stubbed.dir/build.make CMakeFiles/stubbed.dir/stubs/service_module_fibo.cpp.i
.PHONY : stubs/service_module_fibo.cpp.i

stubs/service_module_fibo.s: stubs/service_module_fibo.cpp.s

.PHONY : stubs/service_module_fibo.s

# target to generate assembly for a file
stubs/service_module_fibo.cpp.s:
	$(MAKE) -f CMakeFiles/stubbed.dir/build.make CMakeFiles/stubbed.dir/stubs/service_module_fibo.cpp.s
.PHONY : stubs/service_module_fibo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... stubbed"
	@echo "... web"
	@echo "... lib/engine/default_service.o"
	@echo "... lib/engine/default_service.i"
	@echo "... lib/engine/default_service.s"
	@echo "... lib/engine/engine.o"
	@echo "... lib/engine/engine.i"
	@echo "... lib/engine/engine.s"
	@echo "... lib/engine/http_cache.o"
	@echo "... lib/engine/http_cache.i"
	@echo "... lib/engine/http_cache.s"
	@echo "... lib/engine/http_context.o"
	@echo "... lib/engine/http_context.i"
	@echo "... lib/engine/http_context.s"
	@echo "... lib/engine/http_format.o"
	@echo "... lib/engine/http_format.i"
	@echo "... lib/engine/http_format.s"
	@echo "... lib/engine/http_properties.o"
	@echo "... lib/engine/http_properties.i"
	@echo "... lib/engine/http_properties.s"
	@echo "... lib/engine/http_secured_server.o"
	@echo "... lib/engine/http_secured_server.i"
	@echo "... lib/engine/http_secured_server.s"
	@echo "... lib/engine/http_server.o"
	@echo "... lib/engine/http_server.i"
	@echo "... lib/engine/http_server.s"
	@echo "... lib/engine/recorded_service.o"
	@echo "... lib/engine/recorded_service.i"
	@echo "... lib/engine/recorded_service.s"
	@echo "... lib/engine/service.o"
	@echo "... lib/engine/service.i"
	@echo "... lib/engine/service.s"
	@echo "... lib/engine/service_loader.o"
	@echo "... lib/engine/service_loader.i"
	@echo "... lib/engine/service_loader.s"
	@echo "... lib/engine/service_recorder.o"
	@echo "... lib/engine/service_recorder.i"
	@echo "... lib/engine/service_recorder.s"
	@echo "... lib/http-parser/http_parser.o"
	@echo "... lib/http-parser/http_parser.i"
	@echo "... lib/http-parser/http_parser.s"
	@echo "... lib/utils/Properties.o"
	@echo "... lib/utils/Properties.i"
	@echo "... lib/utils/Properties.s"
	@echo "... lib/utils/advanced_string.o"
	@echo "... lib/utils/advanced_string.i"
	@echo "... lib/utils/advanced_string.s"
	@echo "... lib/utils/compress.o"
	@echo "... lib/utils/compress.i"
	@echo "... lib/utils/compress.s"
	@echo "... lib/utils/demangle.o"
	@echo "... lib/utils/demangle.i"
	@echo "... lib/utils/demangle.s"
	@echo "... lib/utils/files.o"
	@echo "... lib/utils/files.i"
	@echo "... lib/utils/files.s"
	@echo "... lib/utils/jsonxx/jsonxx.o"
	@echo "... lib/utils/jsonxx/jsonxx.i"
	@echo "... lib/utils/jsonxx/jsonxx.s"
	@echo "... lib/utils/trex/trex.o"
	@echo "... lib/utils/trex/trex.i"
	@echo "... lib/utils/trex/trex.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... stubs/service_module_context.o"
	@echo "... stubs/service_module_context.i"
	@echo "... stubs/service_module_context.s"
	@echo "... stubs/service_module_fibo.o"
	@echo "... stubs/service_module_fibo.i"
	@echo "... stubs/service_module_fibo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

